apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: gowtham481/fastapi-app:c4ff515ca8f5670a16a4d8a86618f31ef09b636e
        ports:
        - containerPort: 8080